# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests and QA

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: |
        uv sync --dev
        uv run python -c "from importlib.metadata import version; print(version('cbor2'))" > .cbor2_version
        CBOR2_VERSION=$(cat .cbor2_version)
        CBOR2_BUILD_C_EXTENSION=0 uv pip install --no-binary cbor2 "cbor2==$CBOR2_VERSION" --force-reinstall

    - name: Run linters
      run: |
        uv run black --check .

    - name: Build contracts
      run: |
        bash tests/build_contracts.sh

    - name: Test with pytest
      run: |
        uv run coverage run -m pytest

    - name: Upload coverage data to coveralls.io
      run: uv run coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true


  coveralls:
      name: Indicate completion to coveralls.io
      needs: test
      runs-on: ubuntu-latest
      container: python:3-slim
      steps:
      - name: Install coveralls
        run: pip3 install --upgrade coveralls
      - name: Finished
        run: coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}